"""Export a small, deliberately awkward slice of the master database as SQL.

The checked-in fixture (``master_slice.sql``) is generated by this script, never
hand-written, so it cannot drift from the schema it is meant to represent.
Regenerating it after a schema change is one command:

    uv run python tests/fixtures/build_slice.py

The master database is the one built by ``sulekha`` (see
``sulekha/docs/master_db_runbook.md``). It is not required to run the tests —
only to regenerate the fixture.

Determinism is a hard requirement: running this twice must produce a
byte-identical file, so a diff on the fixture always means the data changed.
That is why every row set carries an explicit ``ORDER BY`` over all its columns
cast to text under the ``C`` collation, and why nothing here writes a timestamp.
"""

from __future__ import annotations

import asyncio
import os
import sys
from pathlib import Path

import asyncpg

MASTER_URL = os.environ.get(
    "MASTER_DATABASE_URL", "postgresql://sambandh:sambandh@localhost:55432/sambandh"
)

OUT_PATH = Path(__file__).with_name("master_slice.sql")

# Rows per INSERT statement. Keeps the file diffable without one statement per row.
BATCH = 200

# Each body is chosen for a case that would otherwise go untested.
# lb_code is the natural key; lb_key is a surrogate and is resolved at runtime.
#
# Muttar is here because "meetings start late" is a comparison, not a property.
# A slice where every body's first meeting year is the same cannot tell a thin
# early year apart from a body that held no meetings — which is exactly the
# distinction the Meetings page has to render. Muttar starts at 2015-2016, the
# earliest year in the whole corpus; Aluva starts eight years later.
BODIES: list[tuple[str, str]] = [
    ("M08032", "Chalakudy Municipality — the worked example, full data"),
    ("M13057", "Mattannur Municipality — finance and meetings but in_elections = false"),
    ("B03024", "Pulikkeezhu Block Panchayat — has_geometry = false"),
    ("M07025", "Aluva Municipality — meetings only from 2023-2024, a late start"),
    ("G04036", "Muttar Grama Panchayat — meetings from 2015-2016, the earliest there is"),
    ("G13064", "Panoor Grama Panchayat — first_cycle = last_cycle = 2010"),
    ("D12001", "Wayanad District Panchayat — the tier that behaves differently"),
]

# Load order is FK-safe: core.local_body is the spine and comes first.
# ``filter_sql`` is applied with the selected lb_keys bound as $1.
TABLES: list[tuple[str, str]] = [
    ("core.local_body", "lb_key = ANY($1)"),
    ("core.lb_coverage", "lb_key = ANY($1)"),
    # Every financial year, unconditionally: fourteen rows, and the site's year
    # controls are meaningless without the full list.
    ("core.financial_year", "true"),
    ("core.lb_sulekha_year", "lb_key = ANY($1)"),
    ("finance.project", "lb_key = ANY($1)"),
    ("finance.lb_year_summary", "lb_key = ANY($1)"),
    ("finance.lb_year_continuity", "lb_key = ANY($1)"),
    ("meetings.meeting", "lb_key = ANY($1)"),
    ("meetings.lb_year_summary", "lb_key = ANY($1)"),
    ("elections.candidate", "lb_key = ANY($1)"),
    ("elections.ward", "lb_key = ANY($1)"),
    ("elections.body_result", "lb_key = ANY($1)"),
]


async def _columns(conn: asyncpg.Connection, table: str) -> list[asyncpg.Record]:
    return await conn.fetch(
        """
        SELECT a.attname AS name,
               format_type(a.atttypid, a.atttypmod) AS coltype,
               a.attnotnull AS notnull
        FROM pg_attribute a
        WHERE a.attrelid = $1::regclass
          AND a.attnum > 0
          AND NOT a.attisdropped
        ORDER BY a.attnum
        """,
        table,
    )


async def _constraints(
    conn: asyncpg.Connection, table: str, kinds: str
) -> list[asyncpg.Record]:
    return await conn.fetch(
        """
        SELECT conname AS name, pg_get_constraintdef(oid) AS def
        FROM pg_constraint
        WHERE conrelid = $1::regclass
          AND contype = ANY($2::char[])
        ORDER BY contype, conname
        """,
        table,
        list(kinds),
    )


def _create_table(table: str, columns: list[asyncpg.Record]) -> str:
    lines = [f"CREATE TABLE {table} ("]
    body = []
    for col in columns:
        null = " NOT NULL" if col["notnull"] else ""
        body.append(f'    "{col["name"]}" {col["coltype"]}{null}')
    lines.append(",\n".join(body))
    lines.append(");")
    return "\n".join(lines)


async def _rows(
    conn: asyncpg.Connection, table: str, filter_sql: str, columns: list[asyncpg.Record],
    lb_keys: list[int],
) -> list[str]:
    """Return each row already rendered as a SQL tuple literal.

    Postgres does the quoting (``quote_nullable``) and the ordering, so escaping
    is correct by construction and the sort does not depend on the client locale.
    """
    names = [c["name"] for c in columns]
    tuple_expr = "'(' || concat_ws(', ', " + ", ".join(
        f'quote_nullable(("{n}")::text)' for n in names
    ) + ") || ')'"
    order_expr = ", ".join(f'("{n}")::text COLLATE "C" ASC NULLS FIRST' for n in names)
    sql = (
        f"SELECT {tuple_expr} AS lit FROM {table} "
        f"WHERE {filter_sql} ORDER BY {order_expr}"
    )
    records = await conn.fetch(sql, lb_keys) if "$1" in filter_sql else await conn.fetch(sql)
    return [r["lit"] for r in records]


async def build() -> str:
    conn = await asyncpg.connect(MASTER_URL)
    try:
        codes = [code for code, _ in BODIES]
        resolved = await conn.fetch(
            "SELECT lb_code, lb_key FROM core.local_body WHERE lb_code = ANY($1) ",
            codes,
        )
        by_code = {r["lb_code"]: r["lb_key"] for r in resolved}
        missing = [c for c in codes if c not in by_code]
        if missing:
            raise SystemExit(f"lb_code not found in core.local_body: {', '.join(missing)}")
        lb_keys = sorted(by_code[c] for c in codes)

        out: list[str] = [
            "-- master_slice.sql — GENERATED by tests/fixtures/build_slice.py. Do not edit.",
            "--",
            f"-- A slice of the Gram Sambandh master database: {len(BODIES)} local bodies and every",
            "-- row they touch. Regenerate with:",
            "--     uv run python tests/fixtures/build_slice.py",
            "--",
            "-- Bodies in this slice:",
        ]
        for code, why in BODIES:
            out.append(f"--   {code} (lb_key {by_code[code]}) — {why}")
        out += [
            "--",
            "-- meetings.artifact, src_* and sakarma are deliberately absent: nothing in",
            "-- the public site reads them, and a test that queries one should fail with a",
            "-- missing-relation error rather than an empty result.",
            "",
            "SET client_min_messages = warning;",
            "",
            "CREATE SCHEMA IF NOT EXISTS core;",
            "CREATE SCHEMA IF NOT EXISTS finance;",
            "CREATE SCHEMA IF NOT EXISTS meetings;",
            "CREATE SCHEMA IF NOT EXISTS elections;",
            "",
        ]

        deferred_fks: list[str] = []
        for table, filter_sql in TABLES:
            columns = await _columns(conn, table)
            rows = await _rows(conn, table, filter_sql, columns, lb_keys)

            out.append(f"-- {table}: {len(rows)} rows")
            out.append(_create_table(table, columns))
            for con in await _constraints(conn, table, "pu"):
                out.append(
                    f'ALTER TABLE {table} ADD CONSTRAINT "{con["name"]}" {con["def"]};'
                )
            for con in await _constraints(conn, table, "f"):
                deferred_fks.append(
                    f'ALTER TABLE {table} ADD CONSTRAINT "{con["name"]}" {con["def"]};'
                )
            out.append("")

            if rows:
                cols_sql = ", ".join(f'"{c["name"]}"' for c in columns)
                for start in range(0, len(rows), BATCH):
                    chunk = rows[start : start + BATCH]
                    out.append(f"INSERT INTO {table} ({cols_sql}) VALUES")
                    out.append(",\n".join(chunk) + ";")
                out.append("")

        if deferred_fks:
            out.append("-- Foreign keys, added after the data so load order cannot break them.")
            out += deferred_fks
            out.append("")

        return "\n".join(out)
    finally:
        await conn.close()


def main() -> int:
    sql = asyncio.run(build())
    previous = OUT_PATH.read_text() if OUT_PATH.exists() else None
    OUT_PATH.write_text(sql)
    if previous is None:
        print(f"wrote {OUT_PATH} ({len(sql):,} bytes)")
    elif previous == sql:
        print(f"{OUT_PATH} unchanged ({len(sql):,} bytes)")
    else:
        print(f"rewrote {OUT_PATH} ({len(sql):,} bytes, was {len(previous):,})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
